name: Build FakeBlueScreen

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 安装必要的工具
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm mingw-w64-x86_64-gcc

      # 编译项目
      - name: Build FakeBlueScreen
        run: |
          gcc -o FakeBlueScreen FakeBlueScreen.c -lgdi32 -luser32

      # 上传编译后的文件
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: FakeBlueScreen-executable
          path: FakeBlueScreen.exe
